services:
  - type: web
    name: bmi-ai-api
    env: python
    plan: free
    pythonVersion: 3.10.14   # 🔥 บังคับใช้ Python 3.10
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
